CCFLAGS = -W -Wall -I..
# executable files for this directory
OBJECTS = add.exe whilecount.exe forcount.exe mysum occurs.exe \
		  item_io.exe add_item.exe add_item2.exe avg_price.exe \
		  exercise1_3.exe exercise1_4.exe exercise1_9.exe exercise1_10.exe exercise1_11.exe \
		  exercise1_12.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

item_io add_item add_item2 avg_price: Sales_item.h
